# Generated by Django 3.2.3 on 2021-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLeader',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('school_name', models.CharField(max_length=70)),
                ('leader_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('badge', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
